// default package
// Generated Dec 30, 2010 12:44:19 PM by Hibernate Tools 3.4.0.Beta1

package org.irdresearch.tbreach.shared.model;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2246273777323799709L;
	private String				pid;
	private String				addressHouse;
	private String				addressStreet;
	private String				addressSector;
	private String				addressCity;
	private String				addressTown;
	private String				addressUc;
	private String				addressLandMark;
	private Integer				cityId;
	private Integer				countryId;
	private Integer				region;
	private String				phone;
	private String				mobile;
	private String				email;
	private String				secondaryAddressHouse;
	private String				secondaryStreetStreet;
	private String				secondaryAddressSector;
	private String				secondaryAddressColony;
	private String				secondaryAddressTown;
	private String				secondaryAddressUc;
	private String				secondaryAddressLandMark;
	private Integer				secondaryCityId;
	private Integer				secondaryCountryId;
	private Integer				secondaryRegion;
	private String				secondaryPhone;
	private String				secondaryMobile;
	private String				secondaryEmail;
	private Float				addressLocationLat;
	private Float				addressLocationLon;
	private Float				secondaryAddressLocationLat;
	private Float				secondaryAddressLocationLon;
	private String				meterNo;
	private String				irdstructureNo;
	private String				secondaryAddressStreet;
	private Integer				houseHoldAdults;
	private Integer				houseHoldChildren;

	public Contact()
	{
		// Not implemented
	}

	public Contact(String pid)
	{
		this.pid = pid;
	}

	public Contact(String pid, String addressHouse, String addressStreet, String addressSector, String addressColony, String addressTown,
			String addressUc, String addressLandMark, Integer cityId, Integer countryId, Integer region, String phone, String mobile, String email,
			String secondaryAddressHouse, String secondaryStreetStreet, String secondaryAddressSector, String secondaryAddressColony,
			String secondaryAddressTown, String secondaryAddressUc, String secondaryAddressLandMark, Integer secondaryCityId,
			Integer secondaryCountryId, Integer secondaryRegion, String secondaryPhone, String secondaryMobile, String secondaryEmail,
			Float addressLocationLat, Float addressLocationLon, Float secondaryAddressLocationLat, Float secondaryAddressLocationLon, String meterNo,
			String irdstructureNo, String secondaryAddressStreet, Integer houseHoldAdults, Integer houseHoldChildren)
	{
		this.pid = pid;
		this.addressHouse = addressHouse;
		this.addressStreet = addressStreet;
		this.addressSector = addressSector;
		this.addressCity = addressColony;
		this.addressTown = addressTown;
		this.addressUc = addressUc;
		this.addressLandMark = addressLandMark;
		this.cityId = cityId;
		this.countryId = countryId;
		this.region = region;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.secondaryAddressHouse = secondaryAddressHouse;
		this.secondaryStreetStreet = secondaryStreetStreet;
		this.secondaryAddressSector = secondaryAddressSector;
		this.secondaryAddressColony = secondaryAddressColony;
		this.secondaryAddressTown = secondaryAddressTown;
		this.secondaryAddressUc = secondaryAddressUc;
		this.secondaryAddressLandMark = secondaryAddressLandMark;
		this.secondaryCityId = secondaryCityId;
		this.secondaryCountryId = secondaryCountryId;
		this.secondaryRegion = secondaryRegion;
		this.secondaryPhone = secondaryPhone;
		this.secondaryMobile = secondaryMobile;
		this.secondaryEmail = secondaryEmail;
		this.addressLocationLat = addressLocationLat;
		this.addressLocationLon = addressLocationLon;
		this.secondaryAddressLocationLat = secondaryAddressLocationLat;
		this.secondaryAddressLocationLon = secondaryAddressLocationLon;
		this.meterNo = meterNo;
		this.irdstructureNo = irdstructureNo;
		this.secondaryAddressStreet = secondaryAddressStreet;
		this.houseHoldAdults = houseHoldAdults;
		this.houseHoldChildren = houseHoldChildren;
	}

	public String getPid()
	{
		return this.pid;
	}

	public void setPid(String pid)
	{
		this.pid = pid;
	}

	public String getAddressHouse()
	{
		return this.addressHouse;
	}

	public void setAddressHouse(String addressHouse)
	{
		this.addressHouse = addressHouse;
	}

	public String getAddressStreet()
	{
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet)
	{
		this.addressStreet = addressStreet;
	}

	public String getAddressSector()
	{
		return this.addressSector;
	}

	public void setAddressSector(String addressSector)
	{
		this.addressSector = addressSector;
	}

	public String getAddressCity()
	{
		return this.addressCity;
	}

	public void setAddressCity(String addressCity)
	{
		this.addressCity = addressCity;
	}

	public String getAddressTown()
	{
		return this.addressTown;
	}

	public void setAddressTown(String addressTown)
	{
		this.addressTown = addressTown;
	}

	public String getAddressUc()
	{
		return this.addressUc;
	}

	public void setAddressUc(String addressUc)
	{
		this.addressUc = addressUc;
	}

	public String getAddressLandMark()
	{
		return this.addressLandMark;
	}

	public void setAddressLandMark(String addressLandMark)
	{
		this.addressLandMark = addressLandMark;
	}

	public Integer getCityId()
	{
		return this.cityId;
	}

	public void setCityId(Integer cityId)
	{
		this.cityId = cityId;
	}

	public Integer getCountryId()
	{
		return this.countryId;
	}

	public void setCountryId(Integer countryId)
	{
		this.countryId = countryId;
	}

	public Integer getRegion()
	{
		return this.region;
	}

	public void setRegion(Integer region)
	{
		this.region = region;
	}

	public String getPhone()
	{
		return this.phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getSecondaryAddressHouse()
	{
		return this.secondaryAddressHouse;
	}

	public void setSecondaryAddressHouse(String secondaryAddressHouse)
	{
		this.secondaryAddressHouse = secondaryAddressHouse;
	}

	public String getSecondaryStreetStreet()
	{
		return this.secondaryStreetStreet;
	}

	public void setSecondaryStreetStreet(String secondaryStreetStreet)
	{
		this.secondaryStreetStreet = secondaryStreetStreet;
	}

	public String getSecondaryAddressSector()
	{
		return this.secondaryAddressSector;
	}

	public void setSecondaryAddressSector(String secondaryAddressSector)
	{
		this.secondaryAddressSector = secondaryAddressSector;
	}

	public String getSecondaryAddressColony()
	{
		return this.secondaryAddressColony;
	}

	public void setSecondaryAddressColony(String secondaryAddressColony)
	{
		this.secondaryAddressColony = secondaryAddressColony;
	}

	public String getSecondaryAddressTown()
	{
		return this.secondaryAddressTown;
	}

	public void setSecondaryAddressTown(String secondaryAddressTown)
	{
		this.secondaryAddressTown = secondaryAddressTown;
	}

	public String getSecondaryAddressUc()
	{
		return this.secondaryAddressUc;
	}

	public void setSecondaryAddressUc(String secondaryAddressUc)
	{
		this.secondaryAddressUc = secondaryAddressUc;
	}

	public String getSecondaryAddressLandMark()
	{
		return this.secondaryAddressLandMark;
	}

	public void setSecondaryAddressLandMark(String secondaryAddressLandMark)
	{
		this.secondaryAddressLandMark = secondaryAddressLandMark;
	}

	public Integer getSecondaryCityId()
	{
		return this.secondaryCityId;
	}

	public void setSecondaryCityId(Integer secondaryCityId)
	{
		this.secondaryCityId = secondaryCityId;
	}

	public Integer getSecondaryCountryId()
	{
		return this.secondaryCountryId;
	}

	public void setSecondaryCountryId(Integer secondaryCountryId)
	{
		this.secondaryCountryId = secondaryCountryId;
	}

	public Integer getSecondaryRegion()
	{
		return this.secondaryRegion;
	}

	public void setSecondaryRegion(Integer secondaryRegion)
	{
		this.secondaryRegion = secondaryRegion;
	}

	public String getSecondaryPhone()
	{
		return this.secondaryPhone;
	}

	public void setSecondaryPhone(String secondaryPhone)
	{
		this.secondaryPhone = secondaryPhone;
	}

	public String getSecondaryMobile()
	{
		return this.secondaryMobile;
	}

	public void setSecondaryMobile(String secondaryMobile)
	{
		this.secondaryMobile = secondaryMobile;
	}

	public String getSecondaryEmail()
	{
		return this.secondaryEmail;
	}

	public void setSecondaryEmail(String secondaryEmail)
	{
		this.secondaryEmail = secondaryEmail;
	}

	public Float getAddressLocationLat()
	{
		return this.addressLocationLat;
	}

	public void setAddressLocationLat(Float addressLocationLat)
	{
		this.addressLocationLat = addressLocationLat;
	}

	public Float getAddressLocationLon()
	{
		return this.addressLocationLon;
	}

	public void setAddressLocationLon(Float addressLocationLon)
	{
		this.addressLocationLon = addressLocationLon;
	}

	public Float getSecondaryAddressLocationLat()
	{
		return this.secondaryAddressLocationLat;
	}

	public void setSecondaryAddressLocationLat(Float secondaryAddressLocationLat)
	{
		this.secondaryAddressLocationLat = secondaryAddressLocationLat;
	}

	public Float getSecondaryAddressLocationLon()
	{
		return this.secondaryAddressLocationLon;
	}

	public void setSecondaryAddressLocationLon(Float secondaryAddressLocationLon)
	{
		this.secondaryAddressLocationLon = secondaryAddressLocationLon;
	}

	public String getMeterNo()
	{
		return this.meterNo;
	}

	public void setMeterNo(String meterNo)
	{
		this.meterNo = meterNo;
	}

	public String getIrdstructureNo()
	{
		return this.irdstructureNo;
	}

	public void setIrdstructureNo(String irdstructureNo)
	{
		this.irdstructureNo = irdstructureNo;
	}

	public String getSecondaryAddressStreet()
	{
		return this.secondaryAddressStreet;
	}

	public void setSecondaryAddressStreet(String secondaryAddressStreet)
	{
		this.secondaryAddressStreet = secondaryAddressStreet;
	}

	public Integer getHouseHoldAdults()
	{
		return this.houseHoldAdults;
	}

	public void setHouseHoldAdults(Integer houseHoldAdults)
	{
		this.houseHoldAdults = houseHoldAdults;
	}

	public Integer getHouseHoldChildren()
	{
		return this.houseHoldChildren;
	}

	public void setHouseHoldChildren(Integer houseHoldChildren)
	{
		this.houseHoldChildren = houseHoldChildren;
	}

	@Override
	public String toString()
	{
		return pid + ", " + addressHouse + ", " + addressStreet + ", " + addressSector + ", " + addressCity + ", " + addressTown + ", " + addressUc
				+ ", " + addressLandMark + ", " + cityId + ", " + countryId + ", " + region + ", " + phone + ", " + mobile + ", " + email + ", "
				+ secondaryAddressHouse + ", " + secondaryStreetStreet + ", " + secondaryAddressSector + ", " + secondaryAddressColony + ", "
				+ secondaryAddressTown + ", " + secondaryAddressUc + ", " + secondaryAddressLandMark + ", " + secondaryCityId + ", "
				+ secondaryCountryId + ", " + secondaryRegion + ", " + secondaryPhone + ", " + secondaryMobile + ", " + secondaryEmail + ", "
				+ addressLocationLat + ", " + addressLocationLon + ", " + secondaryAddressLocationLat + ", " + secondaryAddressLocationLon + ", "
				+ meterNo + ", " + irdstructureNo + ", " + secondaryAddressStreet + ", " + houseHoldAdults + ", " + houseHoldChildren;
	}

}
