package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SetupCountry generated by hbm2java
 */
public class SetupCountry implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 8255096520342233420L;
	private int					countryId;
	private String				countryName;
	private String				shortName;

	public SetupCountry()
	{
		// Not implemented
	}

	public SetupCountry(int countryId, String countryName)
	{
		this.countryId = countryId;
		this.countryName = countryName;
	}

	public SetupCountry(int countryId, String countryName, String shortName)
	{
		this.countryId = countryId;
		this.countryName = countryName;
		this.shortName = shortName;
	}

	public int getCountryId()
	{
		return this.countryId;
	}

	public void setCountryId(int countryId)
	{
		this.countryId = countryId;
	}

	public String getCountryName()
	{
		return this.countryName;
	}

	public void setCountryName(String countryName)
	{
		this.countryName = countryName;
	}

	public String getShortName()
	{
		return this.shortName;
	}

	public void setShortName(String shortName)
	{
		this.shortName = shortName;
	}

	@Override
	public String toString()
	{
		return countryId + ", " + countryName + ", " + shortName;
	}

}
