package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -7133063022452483867L;
	private String				supervisorId;

	public Supervisor()
	{
		// Not implemented
	}

	public Supervisor(String supervisorId)
	{
		this.supervisorId = supervisorId;
	}

	public String getSupervisorId()
	{
		return this.supervisorId;
	}

	public void setSupervisorId(String supervisorId)
	{
		this.supervisorId = supervisorId;
	}

	@Override
	public String toString()
	{
		return supervisorId;
	}

}
