package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * LogDataDelete generated by hbm2java
 */
public class LogDataDelete implements java.io.Serializable
{

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return this.deleteNo + ", " + this.userId + ", " + this.dateDelete + ", " + this.entity + ", " + this.record;
	}

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -592128594175272092L;
	private Long				deleteNo;
	private String				userId;
	private Date				dateDelete;
	private String				entity;
	private String				record;

	public LogDataDelete()
	{
		// Not implemented
	}

	public LogDataDelete(String userId, Date dateDelete, String entity)
	{
		this.userId = userId;
		this.dateDelete = dateDelete;
		this.entity = entity;
	}

	public LogDataDelete(String userId, Date dateDelete, String entity, String record)
	{
		this.userId = userId;
		this.dateDelete = dateDelete;
		this.entity = entity;
		this.record = record;
	}

	public Long getDeleteNo()
	{
		return this.deleteNo;
	}

	public void setDeleteNo(Long deleteNo)
	{
		this.deleteNo = deleteNo;
	}

	public String getUserId()
	{
		return this.userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public Date getDateDelete()
	{
		return this.dateDelete;
	}

	public void setDateDelete(Date dateDelete)
	{
		this.dateDelete = dateDelete;
	}

	public String getEntity()
	{
		return this.entity;
	}

	public void setEntity(String entity)
	{
		this.entity = entity;
	}

	public String getRecord()
	{
		return this.record;
	}

	public void setRecord(String record)
	{
		this.record = record;
	}

}
