package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SetupCity generated by hbm2java
 */
public class SetupCity implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1746360095244528659L;
	private SetupCityId			id;
	private String				cityName;
	private String				shortName;

	public SetupCity()
	{
		// Not implemented
	}

	public SetupCity(SetupCityId id)
	{
		this.id = id;
	}

	public SetupCity(SetupCityId id, String cityName, String shortName)
	{
		this.id = id;
		this.cityName = cityName;
		this.shortName = shortName;
	}

	public SetupCityId getId()
	{
		return this.id;
	}

	public void setId(SetupCityId id)
	{
		this.id = id;
	}

	public String getCityName()
	{
		return this.cityName;
	}

	public void setCityName(String cityName)
	{
		this.cityName = cityName;
	}

	public String getShortName()
	{
		return this.shortName;
	}

	public void setShortName(String shortName)
	{
		this.shortName = shortName;
	}

	@Override
	public String toString()
	{
		return id + ", " + cityName + ", " + shortName;
	}

}
