// default package
// Generated Jan 6, 2011 10:24:45 AM by Hibernate Tools 3.4.0.Beta1
package org.irdresearch.tbreach.shared.model;

import java.util.Date;

/**
 * SputumResults generated by hbm2java
 */
public class SputumResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 835337129767506207L;
	private String				sputumTestId;
	private String				patientId;
	private String				laboratoryId;
	private int					month;
	private Date				dateSubmitted;
	private Date				dateTested;
	private String				testedBy;
	private String				smearResult;
	private String				remarks;
	private String				otherRemarks;

	public SputumResults()
	{
		// Not implemented
	}

	public SputumResults(String sputumTestId, String patientId, int month)
	{
		this.sputumTestId = sputumTestId;
		this.patientId = patientId;
		this.month = month;
	}

	public SputumResults(String sputumTestId, String patientId, String laboratoryId, int irs, int month, Date dateSubmitted, Date dateTested,
			String testedBy, String smearResult, String remarks, String otherRemarks)
	{
		this.sputumTestId = sputumTestId;
		this.patientId = patientId;
		this.laboratoryId = laboratoryId;
		
		this.month = month;
		this.dateSubmitted = dateSubmitted;
		this.dateTested = dateTested;
		this.testedBy = testedBy;
		this.smearResult = smearResult;
		this.remarks = remarks;
		this.otherRemarks = otherRemarks;
	}

	public String getSputumTestId()
	{
		return this.sputumTestId;
	}

	public void setSputumTestId(String sputumTestId)
	{
		this.sputumTestId = sputumTestId;
	}

	public String getPatientId()
	{
		return this.patientId;
	}

	public void setPatientId(String patientId)
	{
		this.patientId = patientId;
	}

	public String getLaboratoryId()
	{
		return this.laboratoryId;
	}

	public void setLaboratoryId(String laboratoryId)
	{
		this.laboratoryId = laboratoryId;
	}

	

	public int getMonth()
	{
		return this.month;
	}

	public void setMonth(int month)
	{
		this.month = month;
	}

	public Date getDateSubmitted()
	{
		return this.dateSubmitted;
	}

	public void setDateSubmitted(Date dateSubmitted)
	{
		this.dateSubmitted = dateSubmitted;
	}

	public Date getDateTested()
	{
		return this.dateTested;
	}

	public void setDateTested(Date dateTested)
	{
		this.dateTested = dateTested;
	}

	public String getTestedBy()
	{
		return this.testedBy;
	}

	public void setTestedBy(String testedBy)
	{
		this.testedBy = testedBy;
	}

	public String getSmearResult()
	{
		return this.smearResult;
	}

	public void setSmearResult(String smearResult)
	{
		this.smearResult = smearResult;
	}

	public String getRemarks()
	{
		return this.remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}

	public String getOtherRemarks()
	{
		return this.otherRemarks;
	}

	public void setOtherRemarks(String otherRemarks)
	{
		this.otherRemarks = otherRemarks;
	}

	@Override
	public String toString()
	{
		return sputumTestId + ", " + patientId + ", " + laboratoryId + ", " + month + ", " + dateSubmitted + ", " + dateTested + ", "
				+ testedBy + ", " + smearResult + ", " + remarks + ", " + otherRemarks;
	}
}
