package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * UserRightsId generated by hbm2java
 */
public class UserRightsId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -8624857490570883281L;
	private String				role;
	private String				menuName;

	public UserRightsId()
	{
		// Not implemented
	}

	public UserRightsId(String role, String menuName)
	{
		this.role = role;
		this.menuName = menuName;
	}

	public String getRole()
	{
		return this.role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	public String getMenuName()
	{
		return this.menuName;
	}

	public void setMenuName(String menuName)
	{
		this.menuName = menuName;
	}

	@Override
	public String toString()
	{
		return role + ", " + menuName;
	}

}
