package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Worker generated by hbm2java
 */
public class Worker implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -8552751696955832053L;
	private String				workerId;
	private String				supervisorId;
	private String				monitorId;

	public Worker()
	{
		// Not implemented
	}

	public Worker(String workerId, String supervisorId, String monitorId)
	{
		this.workerId = workerId;
		this.supervisorId = supervisorId;
		this.monitorId = monitorId;
	}

	public String getWorkerId()
	{
		return this.workerId;
	}

	public void setWorkerId(String workerId)
	{
		this.workerId = workerId;
	}

	public String getSupervisorId()
	{
		return this.supervisorId;
	}

	public void setSupervisorId(String supervisorId)
	{
		this.supervisorId = supervisorId;
	}

	public String getMonitorId()
	{
		return this.monitorId;
	}

	public void setMonitorId(String monitorId)
	{
		this.monitorId = monitorId;
	}

	@Override
	public String toString()
	{
		return workerId + ", " + supervisorId + ", " + monitorId;
	}

}
