// default package
// Generated Jan 6, 2011 10:24:45 AM by Hibernate Tools 3.4.0.Beta1
package org.irdresearch.tbreach.shared.model;

import java.util.Date;

/**
 * XrayResults generated by hbm2java
 */
public class XrayResults implements java.io.Serializable
{
	/**
	 * 
	 */
	private static final long	serialVersionUID	= 7836088134104179786L;
	private XrayResultsId	id;
	private Date			xrayDate;
	private Date			dateReported;
	private String			xrayResults;
	private String			remarks;

	public XrayResults()
	{
		// Not implemented
	}

	public XrayResults(XrayResultsId id)
	{
		this.id = id;
	}

	public XrayResults(XrayResultsId id, Date xrayDate, Date dateReported, String xrayResults, String remarks)
	{
		this.id = id;
		this.xrayDate = xrayDate;
		this.dateReported = dateReported;
		this.xrayResults = xrayResults;
		this.remarks = remarks;
	}

	public XrayResultsId getId()
	{
		return this.id;
	}

	public void setId(XrayResultsId id)
	{
		this.id = id;
	}

	public Date getXrayDate()
	{
		return this.xrayDate;
	}

	public void setXrayDate(Date xrayDate)
	{
		this.xrayDate = xrayDate;
	}

	public Date getDateReported()
	{
		return this.dateReported;
	}

	public void setDateReported(Date dateReported)
	{
		this.dateReported = dateReported;
	}

	public String getXrayResults()
	{
		return this.xrayResults;
	}

	public void setXrayResults(String xrayResults)
	{
		this.xrayResults = xrayResults;
	}

	public String getRemarks()
	{
		return this.remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}

	@Override
	public String toString()
	{
		return id + ", " + xrayDate + ", " + dateReported + ", " + xrayResults + ", " + remarks;
	}
}
