package com.ihsinformatics.xpertsmsweb.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Incentive generated by hbm2java
 */
public class MessageSettings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -335445919499188798L;
	/**
	 * 
	 */

	private Integer settingsId;

	private Boolean sendToPatient;
	private Boolean sendToCenter;
	private Boolean sendToReferenceLocation;
	private Boolean sendToManager;

	private Boolean attachPatientId;
	private Boolean attachSampleId;
	private Boolean attachMtb;
	private Boolean attachRif;
	private Boolean attachOperatorId;
	private Boolean attachLocationId;
	private Boolean attachModuleId;
	private Boolean attachCartridgeId;
	private Boolean attachTestDate;

	private Boolean alertOnAll;
	private Boolean alertOnAllMtb;
	private Boolean alertOnMtbHigh;
	private Boolean alertOnMtbMedium;
	private Boolean alertOnRif;
	private Boolean alertOnError;

	private String programNumber;
	private String managerNumber;

	public MessageSettings() {
	}

	public MessageSettings(Integer settingsId, Boolean sendToPatient,
			Boolean sendToCenter, Boolean sendToReferenceLocation,
			Boolean sendToManager, Boolean attachPatientId,
			Boolean attachSampleId, Boolean attachMtb, Boolean attachRif,
			Boolean attachOperatorId, Boolean attachLocationId,
			Boolean attachModuleId, Boolean attachCartridgeId,
			Boolean attachTestDate, Boolean alertOnAll, Boolean alertOnAllMtb,
			Boolean alertOnMtbHigh, Boolean alertOnMtbMedium,
			Boolean alertOnRif, Boolean alertOnError, String programNumber,
			String managerNumber) {
		super();
		this.settingsId = settingsId;
		this.sendToPatient = sendToPatient;
		this.sendToCenter = sendToCenter;
		this.sendToReferenceLocation = sendToReferenceLocation;
		this.sendToManager = sendToManager;
		this.attachPatientId = attachPatientId;
		this.attachSampleId = attachSampleId;
		this.attachMtb = attachMtb;
		this.attachRif = attachRif;
		this.attachOperatorId = attachOperatorId;
		this.attachLocationId = attachLocationId;
		this.attachModuleId = attachModuleId;
		this.attachCartridgeId = attachCartridgeId;
		this.attachTestDate = attachTestDate;
		this.alertOnAll = alertOnAll;
		this.alertOnAllMtb = alertOnAllMtb;
		this.alertOnMtbHigh = alertOnMtbHigh;
		this.alertOnMtbMedium = alertOnMtbMedium;
		this.alertOnRif = alertOnRif;
		this.alertOnError = alertOnError;
		this.programNumber = programNumber;
		this.managerNumber = managerNumber;
	}

	public Integer getSettingsId() {
		return settingsId;
	}

	public void setSettingsId(Integer settingsId) {
		this.settingsId = settingsId;
	}

	public Boolean getSendToPatient() {
		return sendToPatient;
	}

	public void setSendToPatient(Boolean sendToPatient) {
		this.sendToPatient = sendToPatient;
	}

	public Boolean getSendToCenter() {
		return sendToCenter;
	}

	public void setSendToCenter(Boolean sendToCenter) {
		this.sendToCenter = sendToCenter;
	}

	public Boolean getSendToReferenceLocation() {
		return sendToReferenceLocation;
	}

	public void setSendToReferenceLocation(Boolean sendToReferenceLocation) {
		this.sendToReferenceLocation = sendToReferenceLocation;
	}

	public Boolean getSendToManager() {
		return sendToManager;
	}

	public void setSendToManager(Boolean sendToManager) {
		this.sendToManager = sendToManager;
	}

	public Boolean getAttachPatientId() {
		return attachPatientId;
	}

	public void setAttachPatientId(Boolean attachPatientId) {
		this.attachPatientId = attachPatientId;
	}

	public Boolean getAttachSampleId() {
		return attachSampleId;
	}

	public void setAttachSampleId(Boolean attachSampleId) {
		this.attachSampleId = attachSampleId;
	}

	public Boolean getAttachMtb() {
		return attachMtb;
	}

	public void setAttachMtb(Boolean attachMtb) {
		this.attachMtb = attachMtb;
	}

	public Boolean getAttachRif() {
		return attachRif;
	}

	public void setAttachRif(Boolean attachRif) {
		this.attachRif = attachRif;
	}

	public Boolean getAttachOperatorId() {
		return attachOperatorId;
	}

	public void setAttachOperatorId(Boolean attachOperatorId) {
		this.attachOperatorId = attachOperatorId;
	}

	public Boolean getAttachLocationId() {
		return attachLocationId;
	}

	public void setAttachLocationId(Boolean attachLocationId) {
		this.attachLocationId = attachLocationId;
	}

	public Boolean getAttachModuleId() {
		return attachModuleId;
	}

	public void setAttachModuleId(Boolean attachModuleId) {
		this.attachModuleId = attachModuleId;
	}

	public Boolean getAttachCartridgeId() {
		return attachCartridgeId;
	}

	public void setAttachCartridgeId(Boolean attachCartridgeId) {
		this.attachCartridgeId = attachCartridgeId;
	}

	public Boolean getAttachTestDate() {
		return attachTestDate;
	}

	public void setAttachTestDate(Boolean attachTestDate) {
		this.attachTestDate = attachTestDate;
	}

	public Boolean getAlertOnAll() {
		return alertOnAll;
	}

	public void setAlertOnAll(Boolean alertOnAll) {
		this.alertOnAll = alertOnAll;
	}

	public Boolean getAlertOnAllMtb() {
		return alertOnAllMtb;
	}

	public void setAlertOnAllMtb(Boolean alertOnAllMtb) {
		this.alertOnAllMtb = alertOnAllMtb;
	}

	public Boolean getAlertOnMtbHigh() {
		return alertOnMtbHigh;
	}

	public void setAlertOnMtbHigh(Boolean alertOnMtbHigh) {
		this.alertOnMtbHigh = alertOnMtbHigh;
	}

	public Boolean getAlertOnMtbMedium() {
		return alertOnMtbMedium;
	}

	public void setAlertOnMtbMedium(Boolean alertOnMtbMedium) {
		this.alertOnMtbMedium = alertOnMtbMedium;
	}

	public Boolean getAlertOnRif() {
		return alertOnRif;
	}

	public void setAlertOnRif(Boolean alertOnRif) {
		this.alertOnRif = alertOnRif;
	}

	public Boolean getAlertOnError() {
		return alertOnError;
	}

	public void setAlertOnError(Boolean alertOnError) {
		this.alertOnError = alertOnError;
	}

	public String getProgramNumber() {
		return programNumber;
	}

	public void setProgramNumber(String programNumber) {
		this.programNumber = programNumber;
	}

	public String getManagerNumber() {
		return managerNumber;
	}

	public void setManagerNumber(String managerNumber) {
		this.managerNumber = managerNumber;
	}

	@Override
	public String toString() {
		return settingsId + ", " + sendToPatient + ", " + sendToCenter + ", "
				+ sendToReferenceLocation + ", " + sendToManager + ", "
				+ attachPatientId + ", " + attachSampleId + ", " + attachMtb
				+ ", " + attachRif + ", " + attachOperatorId + ", "
				+ attachLocationId + ", " + attachModuleId + ", "
				+ attachCartridgeId + ", " + attachTestDate + ", " + alertOnAll
				+ ", " + alertOnAllMtb + ", " + alertOnMtbHigh + ", "
				+ alertOnMtbMedium + ", " + alertOnRif + ", " + alertOnError
				+ ", " + programNumber + ", " + managerNumber;
	}
}
