package com.ihsinformatics.xpertsmsweb.shared.model;

import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	private static final long serialVersionUID = 1892494241230445127L;
	private String patientId;
	private String providerId;
	private String firstName;
	private String lastName;
	private String surName;
	private String gender;
	private Date dob;
	private String cnic;
	private String address1;
	private String address2;
	private String town;
	private String landmark;
	private String city;
	private String country;
	private Float latitude;
	private Float longitude;
	private String phone;
	private String mobile;
	private String email;
	private String secondaryAddress1;
	private String secondaryAddress2;
	private String secondaryTown;
	private String secondaryLandmark;
	private String secondaryCity;
	private String secondaryCountry;
	private String secondaryPhone;
	private String secondaryMobile;
	private String secondaryEmail;
	private String mrNo;
	private Float weight;
	private Float height;
	private String bloodGroup;
	private Date dateRegistered;
	private String treatmentCenter;
	private Boolean diseaseSuspected;
	private Boolean diseaseConfirmed;
	private String diseaseCategory;
	private String diseaseSite;
	private String patientStatus;
	private String patientType;
	private String diseaseHistory;
	private String fullDescription;
	
	public Patient() {
		// TODO Auto-generated constructor stub
	}

	public Patient(String patientId, String firstName, String gender) {
		this.patientId = patientId;
		this.firstName = firstName;
		this.gender = gender;
	}

	public Patient(String patientId, String providerId, String mrNo,
			Date dateRegistered, String treatmentCenter, String patientStatus,
			String firstName, String surName, String gender, Date dob) {
		super();
		this.patientId = patientId;
		this.providerId = providerId;
		this.mrNo = mrNo;
		this.dateRegistered = dateRegistered;
		this.treatmentCenter = treatmentCenter;
		this.patientStatus = patientStatus;
		this.firstName = firstName;
		this.surName = surName;
		this.gender = gender;
		this.dob = dob;
	}

	public Patient(String patientId, String providerId, String mrNo,
			Float weight, Float height, String bloodGroup, Date dateRegistered,
			String treatmentCenter, Boolean diseaseSuspected,
			Boolean diseaseConfirmed, String diseaseCategory,
			String diseaseSite, String patientStatus, String patientType,
			String diseaseHistory, String firstName, String lastName,
			String surName, String gender, Date dob, String cnic,
			String address1, String address2, String addressTown,
			String landmark, String addressCity, String addressCountry,
			Float addressLocationLat, Float addressLocationLon, String phone,
			String mobile, String email, String secondaryAddress1,
			String secondaryAddress2, String secondaryTown,
			String secondaryLandMark, String secondaryCity,
			String secondaryCountry, String secondaryPhone,
			String secondaryMobile, String secondaryEmail,
			String fullDescription) {
		super();
		this.patientId = patientId;
		this.providerId = providerId;
		this.mrNo = mrNo;
		this.weight = weight;
		this.height = height;
		this.bloodGroup = bloodGroup;
		this.dateRegistered = dateRegistered;
		this.treatmentCenter = treatmentCenter;
		this.diseaseSuspected = diseaseSuspected;
		this.diseaseConfirmed = diseaseConfirmed;
		this.diseaseCategory = diseaseCategory;
		this.diseaseSite = diseaseSite;
		this.patientStatus = patientStatus;
		this.patientType = patientType;
		this.diseaseHistory = diseaseHistory;
		this.firstName = firstName;
		this.lastName = lastName;
		this.surName = surName;
		this.gender = gender;
		this.dob = dob;
		this.cnic = cnic;
		this.address1 = address1;
		this.address2 = address2;
		this.town = addressTown;
		this.landmark = landmark;
		this.city = addressCity;
		this.country = addressCountry;
		this.latitude = addressLocationLat;
		this.longitude = addressLocationLon;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.secondaryAddress1 = secondaryAddress1;
		this.secondaryAddress2 = secondaryAddress2;
		this.secondaryTown = secondaryTown;
		this.secondaryLandmark = secondaryLandMark;
		this.secondaryCity = secondaryCity;
		this.secondaryCountry = secondaryCountry;
		this.secondaryPhone = secondaryPhone;
		this.secondaryMobile = secondaryMobile;
		this.secondaryEmail = secondaryEmail;
		this.fullDescription = fullDescription;
	}

	public String getPatientId() {
		return patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	public String getProviderId() {
		return providerId;
	}

	public void setProviderId(String providerId) {
		this.providerId = providerId;
	}

	public String getMrNo() {
		return mrNo;
	}

	public void setMrNo(String mrNo) {
		this.mrNo = mrNo;
	}

	public Float getWeight() {
		return weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public Float getHeight() {
		return height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public String getBloodGroup() {
		return bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public Date getDateRegistered() {
		return dateRegistered;
	}

	public void setDateRegistered(Date dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	public String getTreatmentCenter() {
		return treatmentCenter;
	}

	public void setTreatmentCenter(String treatmentCenter) {
		this.treatmentCenter = treatmentCenter;
	}

	public Boolean getDiseaseSuspected() {
		return diseaseSuspected;
	}

	public void setDiseaseSuspected(Boolean diseaseSuspected) {
		this.diseaseSuspected = diseaseSuspected;
	}

	public Boolean getDiseaseConfirmed() {
		return diseaseConfirmed;
	}

	public void setDiseaseConfirmed(Boolean diseaseConfirmed) {
		this.diseaseConfirmed = diseaseConfirmed;
	}

	public String getDiseaseCategory() {
		return diseaseCategory;
	}

	public void setDiseaseCategory(String diseaseCategory) {
		this.diseaseCategory = diseaseCategory;
	}

	public String getDiseaseSite() {
		return diseaseSite;
	}

	public void setDiseaseSite(String diseaseSite) {
		this.diseaseSite = diseaseSite;
	}

	public String getPatientStatus() {
		return patientStatus;
	}

	public void setPatientStatus(String patientStatus) {
		this.patientStatus = patientStatus;
	}

	public String getPatientType() {
		return patientType;
	}

	public void setPatientType(String patientType) {
		this.patientType = patientType;
	}

	public String getDiseaseHistory() {
		return diseaseHistory;
	}

	public void setDiseaseHistory(String diseaseHistory) {
		this.diseaseHistory = diseaseHistory;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getSurname() {
		return surName;
	}

	public void setSurname(String surName) {
		this.surName = surName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getCnic() {
		return cnic;
	}

	public void setCnic(String cnic) {
		this.cnic = cnic;
	}

	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getTown() {
		return town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	public String getLandmark() {
		return landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Float getLatitude() {
		return latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSecondaryAddress1() {
		return secondaryAddress1;
	}

	public void setSecondaryAddress1(String secondaryAddress1) {
		this.secondaryAddress1 = secondaryAddress1;
	}

	public String getSecondaryAddress2() {
		return secondaryAddress2;
	}

	public void setSecondaryAddress2(String secondaryAddress2) {
		this.secondaryAddress2 = secondaryAddress2;
	}

	public String getSecondaryTown() {
		return secondaryTown;
	}

	public void setSecondaryTown(String secondaryTown) {
		this.secondaryTown = secondaryTown;
	}

	public String getSecondaryLandmark() {
		return secondaryLandmark;
	}

	public void setSecondaryLandmark(String secondaryLandmark) {
		this.secondaryLandmark = secondaryLandmark;
	}

	public String getSecondaryCity() {
		return secondaryCity;
	}

	public void setSecondaryCity(String secondaryCity) {
		this.secondaryCity = secondaryCity;
	}

	public String getSecondaryCountry() {
		return secondaryCountry;
	}

	public void setSecondaryCountry(String secondaryCountry) {
		this.secondaryCountry = secondaryCountry;
	}

	public String getSecondaryPhone() {
		return secondaryPhone;
	}

	public void setSecondaryPhone(String secondaryPhone) {
		this.secondaryPhone = secondaryPhone;
	}

	public String getSecondaryMobile() {
		return secondaryMobile;
	}

	public void setSecondaryMobile(String secondaryMobile) {
		this.secondaryMobile = secondaryMobile;
	}

	public String getSecondaryEmail() {
		return secondaryEmail;
	}

	public void setSecondaryEmail(String secondaryEmail) {
		this.secondaryEmail = secondaryEmail;
	}

	public String getFullDescription() {
		return fullDescription;
	}

	public void setFullDescription(String fullDescription) {
		this.fullDescription = fullDescription;
	}

	@Override
	public String toString() {
		return "patientId=" + patientId + ", providerId=" + providerId
				+ ", mrNo=" + mrNo + ", weight=" + weight + ", height="
				+ height + ", bloodGroup=" + bloodGroup + ", dateRegistered="
				+ dateRegistered + ", treatmentCenter=" + treatmentCenter
				+ ", diseaseSuspected=" + diseaseSuspected
				+ ", diseaseConfirmed=" + diseaseConfirmed
				+ ", diseaseCategory=" + diseaseCategory + ", diseaseSite="
				+ diseaseSite + ", patientStatus=" + patientStatus
				+ ", patientType=" + patientType + ", diseaseHistory="
				+ diseaseHistory + ", firstName=" + firstName + ", lastName="
				+ lastName + ", surName=" + surName + ", gender=" + gender
				+ ", dob=" + dob + ", cnic=" + cnic + ", address1=" + address1
				+ ", address2=" + address2 + ", town=" + town + ", landmark="
				+ landmark + ", city=" + city + ", country=" + country
				+ ", latitude=" + latitude + ", longitude=" + longitude
				+ ", phone=" + phone + ", mobile=" + mobile + ", email="
				+ email + ", secondaryAddress1=" + secondaryAddress1
				+ ", secondaryAddress2=" + secondaryAddress2
				+ ", secondaryTown=" + secondaryTown + ", secondaryLandmark="
				+ secondaryLandmark + ", secondaryCity=" + secondaryCity
				+ ", secondaryCountry=" + secondaryCountry
				+ ", secondaryPhone=" + secondaryPhone + ", secondaryMobile="
				+ secondaryMobile + ", secondaryEmail=" + secondaryEmail
				+ ", fullDescription=" + fullDescription;
	}
}
